"""Observer — Position monitoring with stop-loss and take-profit triggers.

Runs daily checks on open positions, monitors P&L against configured
thresholds, and triggers alerts or auto-exit when conditions are met.

Usage:
    observer = Observer()
    alerts = observer.check_positions(positions, account)
    for alert in alerts:
        if alert.should_exit:
            observer.trigger_exit(alert)
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import Any, Callable, Dict, List, Optional

from tradingagents.agents.trader.exit_strategy import ExitReason, ExitStrategy

logger = logging.getLogger(__name__)


class AlertType(str, Enum):
    """Types of position alerts."""
    STOP_LOSS = "stop_loss"
    TAKE_PROFIT = "take_profit"
    TRAILING_STOP = "trailing_stop"
    MARGIN_WARNING = "margin_warning"
    CONCENTRATION = "concentration"
    STALE_POSITION = "stale_position"


@dataclass
class PositionAlert:
    """An alert generated by position monitoring."""
    alert_type: AlertType
    symbol: str
    message: str
    severity: str  # "info", "warning", "critical"
    should_exit: bool  # Whether auto-exit is recommended
    # Position details
    entry_price: float = 0.0
    current_price: float = 0.0
    pnl_pct: float = 0.0
    pnl_amount: float = 0.0
    position_size: float = 0.0
    # Thresholds that triggered
    threshold_value: float = 0.0
    # Metadata
    timestamp: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        result = {
            "alert_type": self.alert_type.value,
            "symbol": self.symbol,
            "message": self.message,
            "severity": self.severity,
            "should_exit": self.should_exit,
            "entry_price": self.entry_price,
            "current_price": self.current_price,
            "pnl_pct": round(self.pnl_pct, 4),
            "pnl_amount": round(self.pnl_amount, 2),
            "position_size": self.position_size,
            "threshold_value": self.threshold_value,
            "timestamp": self.timestamp,
        }
        # Add action field for downstream sell filter compatibility
        if self.should_exit:
            result["action"] = "sell"
        return result


@dataclass
class PositionSnapshot:
    """Snapshot of a position for monitoring."""
    symbol: str
    entry_price: float
    current_price: float
    quantity: int
    side: str  # "long" or "short"
    stop_loss_price: Optional[float] = None
    take_profit_price: Optional[float] = None
    trailing_stop_pct: Optional[float] = None
    highest_price: Optional[float] = None  # For trailing stop
    entry_time: Optional[str] = None

    @property
    def pnl_pct(self) -> float:
        """Calculate P&L percentage."""
        if self.entry_price <= 0:
            return 0.0
        if self.side == "long":
            return (self.current_price - self.entry_price) / self.entry_price
        else:  # short
            return (self.entry_price - self.current_price) / self.entry_price

    @property
    def pnl_amount(self) -> float:
        """Calculate P&L in dollar terms."""
        if self.side == "long":
            return (self.current_price - self.entry_price) * self.quantity
        else:
            return (self.entry_price - self.current_price) * self.quantity

    @property
    def market_value(self) -> float:
        """Current market value of position."""
        return self.current_price * self.quantity


class Observer:
    """Position monitor with configurable risk thresholds.

    Delegates stop-loss, take-profit, and trailing-stop logic to ExitStrategy
    (from tradingagents.agents.trader.exit_strategy) to avoid duplicate
    threshold math.

    Features:
        - Stop-loss / Take-profit / Trailing stop: via ExitStrategy.evaluate()
        - Concentration warning: flag when single position > threshold
        - Stale position: flag positions held too long without movement

    Default thresholds:
        - Stop-loss: -8%
        - Take-profit: +15%
        - Trailing stop: 5% from peak
        - Max concentration: 30% of portfolio
        - Stale days: 30 (no movement > 2%)
    """

    def __init__(
        self,
        stop_loss_pct: float = -0.08,
        take_profit_pct: float = 0.15,
        trailing_stop_pct: float = 0.05,
        max_concentration_pct: float = 0.30,
        stale_days: int = 30,
        max_holding_days: int = 30,
        on_alert: Optional[Callable[[PositionAlert], None]] = None,
        get_history_orders: Optional[Callable[..., List[Dict[str, Any]]]] = None,
    ):
        """Initialize the observer.

        Args:
            stop_loss_pct: Default stop-loss threshold (-0.08 = -8%)
            take_profit_pct: Default take-profit threshold (0.15 = +15%)
            trailing_stop_pct: Trailing stop distance from peak (0.05 = 5%)
            max_concentration_pct: Max single-position concentration (0.30 = 30%)
            stale_days: Days before flagging a stale position (concentration-related)
            max_holding_days: Max days to hold before stale-position exit alert
            on_alert: Optional callback for each alert generated
            get_history_orders: Optional callable to fetch historical orders for
                real entry price resolution (e.g. SimTradingService.get_history_orders)
        """
        self._max_concentration_pct = max_concentration_pct
        self._stale_days = stale_days
        self._max_holding_days = max_holding_days
        self._on_alert = on_alert
        self._alert_history: List[PositionAlert] = []
        self._get_history_orders = get_history_orders

        # W2: Cache real entry prices from history orders to avoid repeated queries
        # Format: {symbol: {"price": float, "timestamp": str}}
        self._entry_prices: Dict[str, Dict[str, Any]] = {}

        # W3: Track when each position was first observed (for stale detection)
        # Format: {symbol: datetime}
        self._first_seen: Dict[str, datetime] = {}

        # P1-6: Delegate exit decisions to ExitStrategy (single source of truth)
        self._exit_strategy = ExitStrategy(
            stop_loss_pct=stop_loss_pct,
            trailing_pct=trailing_stop_pct,
            take_profit_pct=take_profit_pct,
        )

    def check_positions(
        self,
        positions: List[Dict[str, Any]],
        total_assets: float = 0.0,
    ) -> List[PositionAlert]:
        """Check all positions against risk thresholds.

        Args:
            positions: List of position dicts with keys:
                       symbol, entry_price, current_price, quantity, side,
                       stop_loss_price (optional), take_profit_price (optional)
            total_assets: Total portfolio value for concentration checks

        Returns:
            List of PositionAlert objects for positions that triggered alerts
        """
        alerts: List[PositionAlert] = []
        now = datetime.now(timezone.utc).isoformat()

        # P1-6: Map ExitReason → AlertType for unified handling
        _EXIT_REASON_MAP = {
            ExitReason.STOP_LOSS: AlertType.STOP_LOSS,
            ExitReason.TRAILING_STOP: AlertType.TRAILING_STOP,
            ExitReason.TAKE_PROFIT: AlertType.TAKE_PROFIT,
        }
        _SEVERITY_MAP = {
            ExitReason.STOP_LOSS: "critical",
            ExitReason.TRAILING_STOP: "warning",
            ExitReason.TAKE_PROFIT: "info",
        }

        for pos_data in positions:
            # W3: Track first-seen time for stale detection
            sym = pos_data.get("symbol", "")
            if sym and sym not in self._first_seen:
                self._first_seen[sym] = datetime.now(timezone.utc)

            # W2: Resolve real entry price from history orders (cached)
            resolved_price = self._resolve_entry_price(pos_data)
            if resolved_price is not None:
                pos_data = {**pos_data, "entry_price": resolved_price}

            pos = self._parse_position(pos_data)
            if not pos:
                continue

            # P1-6: Delegate stop-loss / trailing / take-profit to ExitStrategy
            decision = self._exit_strategy.evaluate(
                entry_price=pos.entry_price,
                current_price=pos.current_price,
                highest_price=pos.highest_price or pos.current_price,
                side=pos.side,
            )
            if decision.should_exit and decision.reason in _EXIT_REASON_MAP:
                alert_type = _EXIT_REASON_MAP[decision.reason]
                # Take-profit is advisory (should_exit=True but we flag, don't force)
                forced_exit = decision.reason != ExitReason.TAKE_PROFIT
                alerts.append(PositionAlert(
                    alert_type=alert_type,
                    symbol=pos.symbol,
                    message=decision.message,
                    severity=_SEVERITY_MAP[decision.reason],
                    should_exit=forced_exit,
                    entry_price=pos.entry_price,
                    current_price=pos.current_price,
                    pnl_pct=pos.pnl_pct,
                    pnl_amount=pos.pnl_amount,
                    position_size=pos.market_value,
                    threshold_value=decision.threshold,
                    timestamp=now,
                    metadata=decision.metadata,
                ))

            # Check concentration (not part of exit strategy — portfolio-level)
            if total_assets > 0:
                conc_alert = self._check_concentration(pos, total_assets, now)
                if conc_alert:
                    alerts.append(conc_alert)

            # W3: Check stale position (held too long)
            stale_alert = self._check_stale(pos, now)
            if stale_alert:
                alerts.append(stale_alert)

        # Fire callbacks
        for alert in alerts:
            self._alert_history.append(alert)
            if self._on_alert:
                try:
                    self._on_alert(alert)
                except Exception as e:
                    logger.error("Alert callback failed: %s", e)

        if alerts:
            logger.info(
                "Position check: %d alerts generated for %d positions",
                len(alerts), len(positions),
            )

        return alerts

    def _parse_position(self, data: Dict[str, Any]) -> Optional[PositionSnapshot]:
        """Parse position dict into PositionSnapshot."""
        try:
            return PositionSnapshot(
                symbol=data.get("symbol", ""),
                entry_price=float(data.get("entry_price") or data.get("cost_price") or 0),
                current_price=float(data.get("current_price") or data.get("price") or 0),
                quantity=int(data.get("quantity") or data.get("qty") or 0),
                side=data.get("side", "long"),
                stop_loss_price=data.get("stop_loss_price"),
                take_profit_price=data.get("take_profit_price"),
                trailing_stop_pct=data.get("trailing_stop_pct"),
                highest_price=data.get("highest_price"),
                entry_time=data.get("entry_time"),
            )
        except (ValueError, TypeError) as e:
            logger.warning("Failed to parse position: %s", e)
            return None

    def _check_concentration(
        self, pos: PositionSnapshot, total_assets: float, now: str
    ) -> Optional[PositionAlert]:
        """Check if single position exceeds concentration limit."""
        if total_assets <= 0:
            return None

        concentration = pos.market_value / total_assets
        if concentration > self._max_concentration_pct:
            return PositionAlert(
                alert_type=AlertType.CONCENTRATION,
                symbol=pos.symbol,
                message=(
                    f"CONCENTRATION WARNING for {pos.symbol}: "
                    f"{concentration:.1%} of portfolio "
                    f"(limit: {self._max_concentration_pct:.1%})"
                ),
                severity="warning",
                should_exit=False,
                entry_price=pos.entry_price,
                current_price=pos.current_price,
                pnl_pct=pos.pnl_pct,
                pnl_amount=pos.pnl_amount,
                position_size=pos.market_value,
                threshold_value=self._max_concentration_pct,
                timestamp=now,
            )
        return None

    def _resolve_entry_price(self, pos_data: Dict[str, Any]) -> Optional[float]:
        """W2: Resolve real entry price from history orders.

        Queries get_history_orders() for filled buy orders of this symbol,
        picks the earliest dealt_avg_price, and caches the result.
        Returns None if no history order is found (caller should fallback
        to the position snapshot's cost_price).

        Args:
            pos_data: Position dict with at least 'symbol' key.

        Returns:
            Real entry price from history orders, or None if unavailable.
        """
        symbol = pos_data.get("symbol", "")
        if not symbol:
            return None

        # Return cached price if available (W2: 1-hour TTL)
        if symbol in self._entry_prices:
            cached = self._entry_prices[symbol]
            cached_ts = cached.get("timestamp", "")
            if cached_ts:
                try:
                    from datetime import datetime as dt
                    cache_time = dt.fromisoformat(cached_ts.replace("Z", "+00:00"))
                    if (datetime.now(timezone.utc) - cache_time).total_seconds() < 3600:
                        return cached["price"]
                    else:
                        logger.debug("W2: Cache expired for %s, refreshing", symbol)
                        del self._entry_prices[symbol]
                except Exception:
                    return cached["price"]
            else:
                return cached["price"]

        # No history order provider configured — skip
        if self._get_history_orders is None:
            return None

        try:
            # Query filled orders for this symbol
            orders = self._get_history_orders(
                symbol=symbol,
                status_filter=["FILLED_ALL"],
            )
            if not orders:
                logger.debug("No filled history orders for %s", symbol)
                return None

            # Find the earliest filled buy order (earliest create_time)
            # Futu history orders have: dealt_avg_price, order_type (BUY/SELL),
            # create_time, etc.
            buy_orders = [
                o for o in orders
                if str(o.get("order_type", "")).upper() in ("BUY",)
            ]
            if not buy_orders:
                logger.debug("No filled buy orders for %s", symbol)
                return None

            # Sort by create_time ascending, take the first (earliest entry)
            buy_orders.sort(key=lambda o: o.get("create_time", ""))
            earliest = buy_orders[0]
            price = float(earliest.get("dealt_avg_price", 0))
            timestamp = str(earliest.get("create_time", ""))

            if price > 0:
                self._entry_prices[symbol] = {
                    "price": price,
                    "timestamp": timestamp,
                }
                # W3: Use order timestamp for _first_seen instead of observation time
                if symbol not in self._first_seen and timestamp:
                    try:
                        order_time = datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
                        self._first_seen[symbol] = order_time
                        logger.info("W3: Set _first_seen for %s from order time: %s", symbol, timestamp)
                    except Exception:
                        pass
                logger.info(
                    "W2: Resolved entry price for %s: %.4f (from history order at %s)",
                    symbol, price, timestamp,
                )
                return price

        except Exception as e:
            logger.warning("W2: Failed to resolve entry price for %s: %s", symbol, e)

        return None

    def _check_stale(
        self, pos: PositionSnapshot, now: str
    ) -> Optional[PositionAlert]:
        """W3: Check if a position has been held too long (stale).

        Compares the first time this symbol was observed against
        max_holding_days. Returns a STALE_POSITION alert if exceeded.

        Args:
            pos: The position snapshot.
            now: ISO timestamp string for the alert.

        Returns:
            PositionAlert if position is stale, else None.
        """
        first_seen = self._first_seen.get(pos.symbol)
        if first_seen is None:
            return None

        # Calculate holding days from first observation
        utc_now = datetime.now(timezone.utc)
        holding_days = (utc_now - first_seen).days

        if holding_days >= self._max_holding_days:
            return PositionAlert(
                alert_type=AlertType.STALE_POSITION,
                symbol=pos.symbol,
                message=(
                    f"STALE POSITION {pos.symbol}: held for {holding_days} days "
                    f"(max: {self._max_holding_days}). "
                    f"Entry: {pos.entry_price:.4f}, Current: {pos.current_price:.4f}, "
                    f"P&L: {pos.pnl_pct:.2%}"
                ),
                severity="warning",
                should_exit=True,
                entry_price=pos.entry_price,
                current_price=pos.current_price,
                pnl_pct=pos.pnl_pct,
                pnl_amount=pos.pnl_amount,
                position_size=pos.market_value,
                threshold_value=float(self._max_holding_days),
                timestamp=now,
                metadata={
                    "holding_days": holding_days,
                    "max_holding_days": self._max_holding_days,
                    "first_seen_at": first_seen.isoformat(),
                },
            )
        return None

    def get_alert_history(
        self,
        symbol: Optional[str] = None,
        alert_type: Optional[AlertType] = None,
        limit: int = 100,
    ) -> List[PositionAlert]:
        """Get alert history with optional filters."""
        alerts = self._alert_history
        if symbol:
            alerts = [a for a in alerts if a.symbol == symbol]
        if alert_type:
            alerts = [a for a in alerts if a.alert_type == alert_type]
        return alerts[-limit:]

    def clear_history(self) -> None:
        """Clear alert history."""
        self._alert_history.clear()
