"""Observer — Position monitoring with stop-loss and take-profit triggers.

Runs daily checks on open positions, monitors P&L against configured
thresholds, and triggers alerts or auto-exit when conditions are met.

Usage:
    observer = Observer()
    alerts = observer.check_positions(positions, account)
    for alert in alerts:
        if alert.should_exit:
            observer.trigger_exit(alert)
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Callable, Dict, List, Optional

logger = logging.getLogger(__name__)


class AlertType(str, Enum):
    """Types of position alerts."""
    STOP_LOSS = "stop_loss"
    TAKE_PROFIT = "take_profit"
    TRAILING_STOP = "trailing_stop"
    MARGIN_WARNING = "margin_warning"
    CONCENTRATION = "concentration"
    STALE_POSITION = "stale_position"


@dataclass
class PositionAlert:
    """An alert generated by position monitoring."""
    alert_type: AlertType
    symbol: str
    message: str
    severity: str  # "info", "warning", "critical"
    should_exit: bool  # Whether auto-exit is recommended
    # Position details
    entry_price: float = 0.0
    current_price: float = 0.0
    pnl_pct: float = 0.0
    pnl_amount: float = 0.0
    position_size: float = 0.0
    # Thresholds that triggered
    threshold_value: float = 0.0
    # Metadata
    timestamp: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "alert_type": self.alert_type.value,
            "symbol": self.symbol,
            "message": self.message,
            "severity": self.severity,
            "should_exit": self.should_exit,
            "entry_price": self.entry_price,
            "current_price": self.current_price,
            "pnl_pct": round(self.pnl_pct, 4),
            "pnl_amount": round(self.pnl_amount, 2),
            "position_size": self.position_size,
            "threshold_value": self.threshold_value,
            "timestamp": self.timestamp,
        }


@dataclass
class PositionSnapshot:
    """Snapshot of a position for monitoring."""
    symbol: str
    entry_price: float
    current_price: float
    quantity: int
    side: str  # "long" or "short"
    stop_loss_price: Optional[float] = None
    take_profit_price: Optional[float] = None
    trailing_stop_pct: Optional[float] = None
    highest_price: Optional[float] = None  # For trailing stop
    entry_time: Optional[str] = None

    @property
    def pnl_pct(self) -> float:
        """Calculate P&L percentage."""
        if self.entry_price <= 0:
            return 0.0
        if self.side == "long":
            return (self.current_price - self.entry_price) / self.entry_price
        else:  # short
            return (self.entry_price - self.current_price) / self.entry_price

    @property
    def pnl_amount(self) -> float:
        """Calculate P&L in dollar terms."""
        if self.side == "long":
            return (self.current_price - self.entry_price) * self.quantity
        else:
            return (self.entry_price - self.current_price) * self.quantity

    @property
    def market_value(self) -> float:
        """Current market value of position."""
        return self.current_price * self.quantity


class Observer:
    """Position monitor with configurable risk thresholds.

    Features:
        - Stop-loss: auto-exit when loss exceeds threshold
        - Take-profit: alert/exit when profit target hit
        - Trailing stop: dynamic stop that follows price up
        - Concentration warning: flag when single position > threshold
        - Stale position: flag positions held too long without movement

    Default thresholds:
        - Stop-loss: -8%
        - Take-profit: +15%
        - Trailing stop: 5% from peak
        - Max concentration: 30% of portfolio
        - Stale days: 30 (no movement > 2%)
    """

    def __init__(
        self,
        stop_loss_pct: float = -0.08,
        take_profit_pct: float = 0.15,
        trailing_stop_pct: float = 0.05,
        max_concentration_pct: float = 0.30,
        stale_days: int = 30,
        on_alert: Optional[Callable[[PositionAlert], None]] = None,
    ):
        """Initialize the observer.

        Args:
            stop_loss_pct: Default stop-loss threshold (-0.08 = -8%)
            take_profit_pct: Default take-profit threshold (0.15 = +15%)
            trailing_stop_pct: Trailing stop distance from peak (0.05 = 5%)
            max_concentration_pct: Max single-position concentration (0.30 = 30%)
            stale_days: Days before flagging a stale position
            on_alert: Optional callback for each alert generated
        """
        self._stop_loss_pct = stop_loss_pct
        self._take_profit_pct = take_profit_pct
        self._trailing_stop_pct = trailing_stop_pct
        self._max_concentration_pct = max_concentration_pct
        self._stale_days = stale_days
        self._on_alert = on_alert
        self._alert_history: List[PositionAlert] = []

    def check_positions(
        self,
        positions: List[Dict[str, Any]],
        total_assets: float = 0.0,
    ) -> List[PositionAlert]:
        """Check all positions against risk thresholds.

        Args:
            positions: List of position dicts with keys:
                       symbol, entry_price, current_price, quantity, side,
                       stop_loss_price (optional), take_profit_price (optional)
            total_assets: Total portfolio value for concentration checks

        Returns:
            List of PositionAlert objects for positions that triggered alerts
        """
        alerts: List[PositionAlert] = []
        now = datetime.now(timezone.utc).isoformat()

        for pos_data in positions:
            pos = self._parse_position(pos_data)
            if not pos:
                continue

            # Check stop-loss
            sl_alert = self._check_stop_loss(pos, now)
            if sl_alert:
                alerts.append(sl_alert)

            # Check take-profit
            tp_alert = self._check_take_profit(pos, now)
            if tp_alert:
                alerts.append(tp_alert)

            # Check trailing stop
            ts_alert = self._check_trailing_stop(pos, now)
            if ts_alert:
                alerts.append(ts_alert)

            # Check concentration
            if total_assets > 0:
                conc_alert = self._check_concentration(pos, total_assets, now)
                if conc_alert:
                    alerts.append(conc_alert)

        # Fire callbacks
        for alert in alerts:
            self._alert_history.append(alert)
            if self._on_alert:
                try:
                    self._on_alert(alert)
                except Exception as e:
                    logger.error("Alert callback failed: %s", e)

        if alerts:
            logger.info(
                "Position check: %d alerts generated for %d positions",
                len(alerts), len(positions),
            )

        return alerts

    def _parse_position(self, data: Dict[str, Any]) -> Optional[PositionSnapshot]:
        """Parse position dict into PositionSnapshot."""
        try:
            return PositionSnapshot(
                symbol=data.get("symbol", ""),
                entry_price=float(data.get("entry_price") or data.get("cost_price") or 0),
                current_price=float(data.get("current_price") or data.get("price") or 0),
                quantity=int(data.get("quantity") or data.get("qty") or 0),
                side=data.get("side", "long"),
                stop_loss_price=data.get("stop_loss_price"),
                take_profit_price=data.get("take_profit_price"),
                trailing_stop_pct=data.get("trailing_stop_pct"),
                highest_price=data.get("highest_price"),
                entry_time=data.get("entry_time"),
            )
        except (ValueError, TypeError) as e:
            logger.warning("Failed to parse position: %s", e)
            return None

    def _check_stop_loss(
        self, pos: PositionSnapshot, now: str
    ) -> Optional[PositionAlert]:
        """Check if position has hit stop-loss threshold."""
        # Use position-specific stop-loss if set, otherwise use default
        threshold = pos.stop_loss_price
        if threshold:
            should_exit = (
                pos.current_price <= threshold
                if pos.side == "long"
                else pos.current_price >= threshold
            )
        else:
            should_exit = pos.pnl_pct <= self._stop_loss_pct
            threshold = self._stop_loss_pct

        if should_exit:
            return PositionAlert(
                alert_type=AlertType.STOP_LOSS,
                symbol=pos.symbol,
                message=(
                    f"STOP-LOSS triggered for {pos.symbol}: "
                    f"P&L {pos.pnl_pct:+.1%} (threshold: {threshold})"
                ),
                severity="critical",
                should_exit=True,
                entry_price=pos.entry_price,
                current_price=pos.current_price,
                pnl_pct=pos.pnl_pct,
                pnl_amount=pos.pnl_amount,
                position_size=pos.market_value,
                threshold_value=threshold if isinstance(threshold, (int, float)) else 0,
                timestamp=now,
            )
        return None

    def _check_take_profit(
        self, pos: PositionSnapshot, now: str
    ) -> Optional[PositionAlert]:
        """Check if position has hit take-profit target."""
        threshold = pos.take_profit_price
        if threshold:
            should_exit = (
                pos.current_price >= threshold
                if pos.side == "long"
                else pos.current_price <= threshold
            )
        else:
            should_exit = pos.pnl_pct >= self._take_profit_pct
            threshold = self._take_profit_pct

        if should_exit:
            return PositionAlert(
                alert_type=AlertType.TAKE_PROFIT,
                symbol=pos.symbol,
                message=(
                    f"TAKE-PROFIT reached for {pos.symbol}: "
                    f"P&L {pos.pnl_pct:+.1%} (target: {threshold})"
                ),
                severity="info",
                should_exit=False,  # Take-profit is advisory, not forced
                entry_price=pos.entry_price,
                current_price=pos.current_price,
                pnl_pct=pos.pnl_pct,
                pnl_amount=pos.pnl_amount,
                position_size=pos.market_value,
                threshold_value=threshold if isinstance(threshold, (int, float)) else 0,
                timestamp=now,
            )
        return None

    def _check_trailing_stop(
        self, pos: PositionSnapshot, now: str
    ) -> Optional[PositionAlert]:
        """Check trailing stop (price dropped X% from peak)."""
        if pos.side != "long":
            return None  # Trailing stop only for long positions

        highest = pos.highest_price or pos.current_price
        trailing_pct = pos.trailing_stop_pct or self._trailing_stop_pct

        if highest <= 0:
            return None

        # Price has dropped trailing_pct from the highest
        drop_from_peak = (highest - pos.current_price) / highest
        if drop_from_peak >= trailing_pct:
            return PositionAlert(
                alert_type=AlertType.TRAILING_STOP,
                symbol=pos.symbol,
                message=(
                    f"TRAILING STOP for {pos.symbol}: "
                    f"dropped {drop_from_peak:.1%} from peak {highest:.2f} "
                    f"(threshold: {trailing_pct:.1%})"
                ),
                severity="warning",
                should_exit=True,
                entry_price=pos.entry_price,
                current_price=pos.current_price,
                pnl_pct=pos.pnl_pct,
                pnl_amount=pos.pnl_amount,
                position_size=pos.market_value,
                threshold_value=trailing_pct,
                timestamp=now,
                metadata={"highest_price": highest, "drop_from_peak": drop_from_peak},
            )
        return None

    def _check_concentration(
        self, pos: PositionSnapshot, total_assets: float, now: str
    ) -> Optional[PositionAlert]:
        """Check if single position exceeds concentration limit."""
        if total_assets <= 0:
            return None

        concentration = pos.market_value / total_assets
        if concentration > self._max_concentration_pct:
            return PositionAlert(
                alert_type=AlertType.CONCENTRATION,
                symbol=pos.symbol,
                message=(
                    f"CONCENTRATION WARNING for {pos.symbol}: "
                    f"{concentration:.1%} of portfolio "
                    f"(limit: {self._max_concentration_pct:.1%})"
                ),
                severity="warning",
                should_exit=False,
                entry_price=pos.entry_price,
                current_price=pos.current_price,
                pnl_pct=pos.pnl_pct,
                pnl_amount=pos.pnl_amount,
                position_size=pos.market_value,
                threshold_value=self._max_concentration_pct,
                timestamp=now,
            )
        return None

    def get_alert_history(
        self,
        symbol: Optional[str] = None,
        alert_type: Optional[AlertType] = None,
        limit: int = 100,
    ) -> List[PositionAlert]:
        """Get alert history with optional filters."""
        alerts = self._alert_history
        if symbol:
            alerts = [a for a in alerts if a.symbol == symbol]
        if alert_type:
            alerts = [a for a in alerts if a.alert_type == alert_type]
        return alerts[-limit:]

    def clear_history(self) -> None:
        """Clear alert history."""
        self._alert_history.clear()
